### ISSUE TITLE
Add icon for the Cohere language model

### ISSUE THREAD

**Issue by adubovik** [epam/ai-dial-chat-themes#20]
Required for https://github.com/epam/ai-dial-adapter-bedrock/issues/30

Relevant links:

* [Cohere chat](https://docs.cohere.com/docs/cochat-beta) (`cohere.command-text-v14` LLM)
* Cohere [favicon](https://files.readme.io/8028ad6-small-cohere-icon.png)
* [SVG](https://a.b.cdn.console.awsstatic.com/a/v1/MLTNQNCYGMAFS6P2EL34CP4TFPGXFDKQJJSYVFB4CYOMOAWJ3GVQ/images/cohere_24x24.svg) from the [Bedrock page](https://us-east-1.console.aws.amazon.com/bedrock/home?region=us-east-1#/providers?model=cohere.command-text-v14) _(based on PNG :( )_.

**Comment by mikitabut** [comment]
@adubovik We will use image provided by designer for cohere icon
